require:
    - rubocop-capybara
    - rubocop-rspec
    - rubocop-rails

Layout/ArgumentAlignment:
    EnforcedStyle: with_first_argument
Layout/ArrayAlignment:
    Enabled: true
    EnforcedStyle: with_first_element
Layout/IndentationStyle:
    Enabled: true
    IndentationWidth: 4
    EnforcedStyle: spaces
Layout/IndentationWidth:
    Width: 4
Metrics/ClassLength:
    Max: 400
Metrics/MethodLength:
    Max: 100

AllCops:
    # Suggestextensions: false
    Exclude:
        - "node_modules/**/*"
        - "tmp/**/*"
        - "vendor/**/*"
        - ".git/**/*"
